[package]
name = "tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5"
pest-tools = { path = "../../pest-tools" }
pest_derive = "2.5"
spark-ml = { path = ".." }
