[package]
name = "spark-ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9"
once_cell = "1.9"
pest = "2.5"
pest_derive = "2.5"
regex = "1.7"
